// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::abs as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "@",
        &[
            Pair {
                left: None,
                right: "v_float4",
                dsl: dsl::float4,
            },
            Pair {
                left: None,
                right: "v_float8",
                dsl: dsl::float8,
            },
            Pair {
                left: None,
                right: "v_int2",
                dsl: dsl::int2,
            },
            Pair {
                left: None,
                right: "v_int4",
                dsl: dsl::int4,
            },
            Pair {
                left: None,
                right: "v_int8",
                dsl: dsl::int8,
            },
            Pair {
                left: None,
                right: "v_numeric",
                dsl: dsl::numeric,
            },
        ],
    );
}
