// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::closest_point as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "##",
        &[
            Pair {
                left: Some("v_line"),
                right: "v_lseg",
                dsl: dsl::line_lseg,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_box",
                dsl: dsl::lseg_box,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_lseg",
                dsl: dsl::lseg_lseg,
            },
            Pair {
                left: Some("v_point"),
                right: "v_box",
                dsl: dsl::point_box,
            },
            Pair {
                left: Some("v_point"),
                right: "v_line",
                dsl: dsl::point_line,
            },
            Pair {
                left: Some("v_point"),
                right: "v_lseg",
                dsl: dsl::point_lseg,
            },
        ],
    );
}
