// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::concat as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "||",
        &[
            Pair {
                left: Some("v_bit"),
                right: "v_text",
                dsl: dsl::bit_text,
            },
            Pair {
                left: Some("v_bool"),
                right: "v_text",
                dsl: dsl::bool_text,
            },
            Pair {
                left: Some("v_box"),
                right: "v_text",
                dsl: dsl::box_text,
            },
            Pair {
                left: Some("v_bpchar"),
                right: "v_text",
                dsl: dsl::bpchar_text,
            },
            Pair {
                left: Some("v_bytea"),
                right: "v_bytea",
                dsl: dsl::bytea_bytea,
            },
            Pair {
                left: Some("v_bytea"),
                right: "v_text",
                dsl: dsl::bytea_text,
            },
            Pair {
                left: Some("v_char"),
                right: "v_text",
                dsl: dsl::char_text,
            },
            Pair {
                left: Some("v_cidr"),
                right: "v_text",
                dsl: dsl::cidr_text,
            },
            Pair {
                left: Some("v_circle"),
                right: "v_text",
                dsl: dsl::circle_text,
            },
            Pair {
                left: Some("v_date"),
                right: "v_text",
                dsl: dsl::date_text,
            },
            Pair {
                left: Some("v_float4"),
                right: "v_text",
                dsl: dsl::float4_text,
            },
            Pair {
                left: Some("v_float8"),
                right: "v_text",
                dsl: dsl::float8_text,
            },
            Pair {
                left: Some("v_inet"),
                right: "v_text",
                dsl: dsl::inet_text,
            },
            Pair {
                left: Some("v_int2"),
                right: "v_text",
                dsl: dsl::int2_text,
            },
            Pair {
                left: Some("v_int4_array"),
                right: "v_int4",
                dsl: dsl::int4_array_int4,
            },
            Pair {
                left: Some("v_int4_array"),
                right: "v_int4_array",
                dsl: dsl::int4_array_int4_array,
            },
            Pair {
                left: Some("v_int4"),
                right: "v_int4_array",
                dsl: dsl::int4_int4_array,
            },
            Pair {
                left: Some("v_int4"),
                right: "v_text",
                dsl: dsl::int4_text,
            },
            Pair {
                left: Some("v_int4multirange"),
                right: "v_text",
                dsl: dsl::int4multirange_text,
            },
            Pair {
                left: Some("v_int4range"),
                right: "v_text",
                dsl: dsl::int4range_text,
            },
            Pair {
                left: Some("v_int8"),
                right: "v_text",
                dsl: dsl::int8_text,
            },
            Pair {
                left: Some("v_interval"),
                right: "v_text",
                dsl: dsl::interval_text,
            },
            Pair {
                left: Some("v_json"),
                right: "v_text",
                dsl: dsl::json_text,
            },
            Pair {
                left: Some("v_jsonb"),
                right: "v_jsonb",
                dsl: dsl::jsonb_jsonb,
            },
            Pair {
                left: Some("v_jsonb"),
                right: "v_text",
                dsl: dsl::jsonb_text,
            },
            Pair {
                left: Some("v_jsonpath"),
                right: "v_text",
                dsl: dsl::jsonpath_text,
            },
            Pair {
                left: Some("v_line"),
                right: "v_text",
                dsl: dsl::line_text,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_text",
                dsl: dsl::lseg_text,
            },
            Pair {
                left: Some("v_macaddr8"),
                right: "v_text",
                dsl: dsl::macaddr8_text,
            },
            Pair {
                left: Some("v_macaddr"),
                right: "v_text",
                dsl: dsl::macaddr_text,
            },
            Pair {
                left: Some("v_money"),
                right: "v_text",
                dsl: dsl::money_text,
            },
            Pair {
                left: Some("v_mood"),
                right: "v_text",
                dsl: dsl::mood_text,
            },
            Pair {
                left: Some("v_numeric"),
                right: "v_text",
                dsl: dsl::numeric_text,
            },
            Pair {
                left: Some("v_path"),
                right: "v_text",
                dsl: dsl::path_text,
            },
            Pair {
                left: Some("v_point"),
                right: "v_text",
                dsl: dsl::point_text,
            },
            Pair {
                left: Some("v_polygon"),
                right: "v_text",
                dsl: dsl::polygon_text,
            },
            Pair {
                left: Some("v_price_tag"),
                right: "v_text",
                dsl: dsl::price_tag_text,
            },
            Pair {
                left: Some("v_text_array"),
                right: "v_text",
                dsl: dsl::text_array_text,
            },
            Pair {
                left: Some("v_text_array"),
                right: "v_text_array",
                dsl: dsl::text_array_text_array,
            },
            Pair {
                left: Some("v_text"),
                right: "v_bit",
                dsl: dsl::text_bit,
            },
            Pair {
                left: Some("v_text"),
                right: "v_bool",
                dsl: dsl::text_bool,
            },
            Pair {
                left: Some("v_text"),
                right: "v_box",
                dsl: dsl::text_box,
            },
            Pair {
                left: Some("v_text"),
                right: "v_bpchar",
                dsl: dsl::text_bpchar,
            },
            Pair {
                left: Some("v_text"),
                right: "v_bytea",
                dsl: dsl::text_bytea,
            },
            Pair {
                left: Some("v_text"),
                right: "v_char",
                dsl: dsl::text_char,
            },
            Pair {
                left: Some("v_text"),
                right: "v_cidr",
                dsl: dsl::text_cidr,
            },
            Pair {
                left: Some("v_text"),
                right: "v_circle",
                dsl: dsl::text_circle,
            },
            Pair {
                left: Some("v_text"),
                right: "v_date",
                dsl: dsl::text_date,
            },
            Pair {
                left: Some("v_text"),
                right: "v_float4",
                dsl: dsl::text_float4,
            },
            Pair {
                left: Some("v_text"),
                right: "v_float8",
                dsl: dsl::text_float8,
            },
            Pair {
                left: Some("v_text"),
                right: "v_inet",
                dsl: dsl::text_inet,
            },
            Pair {
                left: Some("v_text"),
                right: "v_int2",
                dsl: dsl::text_int2,
            },
            Pair {
                left: Some("v_text"),
                right: "v_int4",
                dsl: dsl::text_int4,
            },
            Pair {
                left: Some("v_text"),
                right: "v_int4multirange",
                dsl: dsl::text_int4multirange,
            },
            Pair {
                left: Some("v_text"),
                right: "v_int4range",
                dsl: dsl::text_int4range,
            },
            Pair {
                left: Some("v_text"),
                right: "v_int8",
                dsl: dsl::text_int8,
            },
            Pair {
                left: Some("v_text"),
                right: "v_interval",
                dsl: dsl::text_interval,
            },
            Pair {
                left: Some("v_text"),
                right: "v_json",
                dsl: dsl::text_json,
            },
            Pair {
                left: Some("v_text"),
                right: "v_jsonb",
                dsl: dsl::text_jsonb,
            },
            Pair {
                left: Some("v_text"),
                right: "v_jsonpath",
                dsl: dsl::text_jsonpath,
            },
            Pair {
                left: Some("v_text"),
                right: "v_line",
                dsl: dsl::text_line,
            },
            Pair {
                left: Some("v_text"),
                right: "v_lseg",
                dsl: dsl::text_lseg,
            },
            Pair {
                left: Some("v_text"),
                right: "v_macaddr",
                dsl: dsl::text_macaddr,
            },
            Pair {
                left: Some("v_text"),
                right: "v_macaddr8",
                dsl: dsl::text_macaddr8,
            },
            Pair {
                left: Some("v_text"),
                right: "v_money",
                dsl: dsl::text_money,
            },
            Pair {
                left: Some("v_text"),
                right: "v_mood",
                dsl: dsl::text_mood,
            },
            Pair {
                left: Some("v_text"),
                right: "v_numeric",
                dsl: dsl::text_numeric,
            },
            Pair {
                left: Some("v_text"),
                right: "v_path",
                dsl: dsl::text_path,
            },
            Pair {
                left: Some("v_text"),
                right: "v_point",
                dsl: dsl::text_point,
            },
            Pair {
                left: Some("v_text"),
                right: "v_polygon",
                dsl: dsl::text_polygon,
            },
            Pair {
                left: Some("v_text"),
                right: "v_price_tag",
                dsl: dsl::text_price_tag,
            },
            Pair {
                left: Some("v_text"),
                right: "v_text",
                dsl: dsl::text_text,
            },
            Pair {
                left: Some("v_text"),
                right: "v_text_array",
                dsl: dsl::text_text_array,
            },
            Pair {
                left: Some("v_text"),
                right: "v_time",
                dsl: dsl::text_time,
            },
            Pair {
                left: Some("v_text"),
                right: "v_timestamp",
                dsl: dsl::text_timestamp,
            },
            Pair {
                left: Some("v_text"),
                right: "v_timestamptz",
                dsl: dsl::text_timestamptz,
            },
            Pair {
                left: Some("v_text"),
                right: "v_timetz",
                dsl: dsl::text_timetz,
            },
            Pair {
                left: Some("v_text"),
                right: "v_tsquery",
                dsl: dsl::text_tsquery,
            },
            Pair {
                left: Some("v_text"),
                right: "v_tsrange",
                dsl: dsl::text_tsrange,
            },
            Pair {
                left: Some("v_text"),
                right: "v_tsvector",
                dsl: dsl::text_tsvector,
            },
            Pair {
                left: Some("v_text"),
                right: "v_uuid",
                dsl: dsl::text_uuid,
            },
            Pair {
                left: Some("v_text"),
                right: "v_varbit",
                dsl: dsl::text_varbit,
            },
            Pair {
                left: Some("v_text"),
                right: "v_varchar",
                dsl: dsl::text_varchar,
            },
            Pair {
                left: Some("v_text"),
                right: "v_xml",
                dsl: dsl::text_xml,
            },
            Pair {
                left: Some("v_time"),
                right: "v_text",
                dsl: dsl::time_text,
            },
            Pair {
                left: Some("v_timestamp"),
                right: "v_text",
                dsl: dsl::timestamp_text,
            },
            Pair {
                left: Some("v_timestamptz"),
                right: "v_text",
                dsl: dsl::timestamptz_text,
            },
            Pair {
                left: Some("v_timetz"),
                right: "v_text",
                dsl: dsl::timetz_text,
            },
            Pair {
                left: Some("v_tsquery"),
                right: "v_text",
                dsl: dsl::tsquery_text,
            },
            Pair {
                left: Some("v_tsquery"),
                right: "v_tsquery",
                dsl: dsl::tsquery_tsquery,
            },
            Pair {
                left: Some("v_tsrange"),
                right: "v_text",
                dsl: dsl::tsrange_text,
            },
            Pair {
                left: Some("v_tsvector"),
                right: "v_text",
                dsl: dsl::tsvector_text,
            },
            Pair {
                left: Some("v_tsvector"),
                right: "v_tsvector",
                dsl: dsl::tsvector_tsvector,
            },
            Pair {
                left: Some("v_uuid"),
                right: "v_text",
                dsl: dsl::uuid_text,
            },
            Pair {
                left: Some("v_varbit"),
                right: "v_text",
                dsl: dsl::varbit_text,
            },
            Pair {
                left: Some("v_varbit"),
                right: "v_varbit",
                dsl: dsl::varbit_varbit,
            },
            Pair {
                left: Some("v_varchar"),
                right: "v_text",
                dsl: dsl::varchar_text,
            },
            Pair {
                left: Some("v_xml"),
                right: "v_text",
                dsl: dsl::xml_text,
            },
        ],
    );
}
