// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::contained_by as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "<@",
        &[
            Pair {
                left: Some("v_box"),
                right: "v_box",
                dsl: dsl::box_box,
            },
            Pair {
                left: Some("v_circle"),
                right: "v_circle",
                dsl: dsl::circle_circle,
            },
            Pair {
                left: Some("v_int4_array"),
                right: "v_int4_array",
                dsl: dsl::int4_array_int4_array,
            },
            Pair {
                left: Some("v_int4"),
                right: "v_int4multirange",
                dsl: dsl::int4_int4multirange,
            },
            Pair {
                left: Some("v_int4"),
                right: "v_int4range",
                dsl: dsl::int4_int4range,
            },
            Pair {
                left: Some("v_int4multirange"),
                right: "v_int4multirange",
                dsl: dsl::int4multirange_int4multirange,
            },
            Pair {
                left: Some("v_int4multirange"),
                right: "v_int4range",
                dsl: dsl::int4multirange_int4range,
            },
            Pair {
                left: Some("v_int4range"),
                right: "v_int4multirange",
                dsl: dsl::int4range_int4multirange,
            },
            Pair {
                left: Some("v_int4range"),
                right: "v_int4range",
                dsl: dsl::int4range_int4range,
            },
            Pair {
                left: Some("v_jsonb"),
                right: "v_jsonb",
                dsl: dsl::jsonb_jsonb,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_box",
                dsl: dsl::lseg_box,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_line",
                dsl: dsl::lseg_line,
            },
            Pair {
                left: Some("v_point"),
                right: "v_box",
                dsl: dsl::point_box,
            },
            Pair {
                left: Some("v_point"),
                right: "v_circle",
                dsl: dsl::point_circle,
            },
            Pair {
                left: Some("v_point"),
                right: "v_line",
                dsl: dsl::point_line,
            },
            Pair {
                left: Some("v_point"),
                right: "v_lseg",
                dsl: dsl::point_lseg,
            },
            Pair {
                left: Some("v_point"),
                right: "v_path",
                dsl: dsl::point_path,
            },
            Pair {
                left: Some("v_point"),
                right: "v_polygon",
                dsl: dsl::point_polygon,
            },
            Pair {
                left: Some("v_polygon"),
                right: "v_polygon",
                dsl: dsl::polygon_polygon,
            },
            Pair {
                left: Some("v_text_array"),
                right: "v_text_array",
                dsl: dsl::text_array_text_array,
            },
            Pair {
                left: Some("v_timestamp"),
                right: "v_tsrange",
                dsl: dsl::timestamp_tsrange,
            },
            Pair {
                left: Some("v_tsquery"),
                right: "v_tsquery",
                dsl: dsl::tsquery_tsquery,
            },
            Pair {
                left: Some("v_tsrange"),
                right: "v_tsrange",
                dsl: dsl::tsrange_tsrange,
            },
        ],
    );
}
