// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::distance as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "<->",
        &[
            Pair {
                left: Some("v_box"),
                right: "v_box",
                dsl: dsl::box_box,
            },
            Pair {
                left: Some("v_box"),
                right: "v_lseg",
                dsl: dsl::box_lseg,
            },
            Pair {
                left: Some("v_box"),
                right: "v_point",
                dsl: dsl::box_point,
            },
            Pair {
                left: Some("v_circle"),
                right: "v_circle",
                dsl: dsl::circle_circle,
            },
            Pair {
                left: Some("v_circle"),
                right: "v_point",
                dsl: dsl::circle_point,
            },
            Pair {
                left: Some("v_circle"),
                right: "v_polygon",
                dsl: dsl::circle_polygon,
            },
            Pair {
                left: Some("v_line"),
                right: "v_line",
                dsl: dsl::line_line,
            },
            Pair {
                left: Some("v_line"),
                right: "v_lseg",
                dsl: dsl::line_lseg,
            },
            Pair {
                left: Some("v_line"),
                right: "v_point",
                dsl: dsl::line_point,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_box",
                dsl: dsl::lseg_box,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_line",
                dsl: dsl::lseg_line,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_lseg",
                dsl: dsl::lseg_lseg,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_point",
                dsl: dsl::lseg_point,
            },
            Pair {
                left: Some("v_path"),
                right: "v_path",
                dsl: dsl::path_path,
            },
            Pair {
                left: Some("v_path"),
                right: "v_point",
                dsl: dsl::path_point,
            },
            Pair {
                left: Some("v_point"),
                right: "v_box",
                dsl: dsl::point_box,
            },
            Pair {
                left: Some("v_point"),
                right: "v_circle",
                dsl: dsl::point_circle,
            },
            Pair {
                left: Some("v_point"),
                right: "v_line",
                dsl: dsl::point_line,
            },
            Pair {
                left: Some("v_point"),
                right: "v_lseg",
                dsl: dsl::point_lseg,
            },
            Pair {
                left: Some("v_point"),
                right: "v_path",
                dsl: dsl::point_path,
            },
            Pair {
                left: Some("v_point"),
                right: "v_point",
                dsl: dsl::point_point,
            },
            Pair {
                left: Some("v_point"),
                right: "v_polygon",
                dsl: dsl::point_polygon,
            },
            Pair {
                left: Some("v_polygon"),
                right: "v_circle",
                dsl: dsl::polygon_circle,
            },
            Pair {
                left: Some("v_polygon"),
                right: "v_point",
                dsl: dsl::polygon_point,
            },
            Pair {
                left: Some("v_polygon"),
                right: "v_polygon",
                dsl: dsl::polygon_polygon,
            },
            Pair {
                left: Some("v_tsquery"),
                right: "v_tsquery",
                dsl: dsl::tsquery_tsquery,
            },
        ],
    );
}
