// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::div as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "/",
        &[
            Pair {
                left: Some("v_box"),
                right: "v_point",
                dsl: dsl::box_point,
            },
            Pair {
                left: Some("v_circle"),
                right: "v_point",
                dsl: dsl::circle_point,
            },
            Pair {
                left: Some("v_float4"),
                right: "v_float4",
                dsl: dsl::float4_float4,
            },
            Pair {
                left: Some("v_float4"),
                right: "v_float8",
                dsl: dsl::float4_float8,
            },
            Pair {
                left: Some("v_float8"),
                right: "v_float4",
                dsl: dsl::float8_float4,
            },
            Pair {
                left: Some("v_float8"),
                right: "v_float8",
                dsl: dsl::float8_float8,
            },
            Pair {
                left: Some("v_int2"),
                right: "v_int2",
                dsl: dsl::int2_int2,
            },
            Pair {
                left: Some("v_int2"),
                right: "v_int4",
                dsl: dsl::int2_int4,
            },
            Pair {
                left: Some("v_int2"),
                right: "v_int8",
                dsl: dsl::int2_int8,
            },
            Pair {
                left: Some("v_int4"),
                right: "v_int2",
                dsl: dsl::int4_int2,
            },
            Pair {
                left: Some("v_int4"),
                right: "v_int4",
                dsl: dsl::int4_int4,
            },
            Pair {
                left: Some("v_int4"),
                right: "v_int8",
                dsl: dsl::int4_int8,
            },
            Pair {
                left: Some("v_int8"),
                right: "v_int2",
                dsl: dsl::int8_int2,
            },
            Pair {
                left: Some("v_int8"),
                right: "v_int4",
                dsl: dsl::int8_int4,
            },
            Pair {
                left: Some("v_int8"),
                right: "v_int8",
                dsl: dsl::int8_int8,
            },
            Pair {
                left: Some("v_interval"),
                right: "v_float8",
                dsl: dsl::interval_float8,
            },
            Pair {
                left: Some("v_money"),
                right: "v_float4",
                dsl: dsl::money_float4,
            },
            Pair {
                left: Some("v_money"),
                right: "v_float8",
                dsl: dsl::money_float8,
            },
            Pair {
                left: Some("v_money"),
                right: "v_int2",
                dsl: dsl::money_int2,
            },
            Pair {
                left: Some("v_money"),
                right: "v_int4",
                dsl: dsl::money_int4,
            },
            Pair {
                left: Some("v_money"),
                right: "v_int8",
                dsl: dsl::money_int8,
            },
            Pair {
                left: Some("v_money"),
                right: "v_money",
                dsl: dsl::money_money,
            },
            Pair {
                left: Some("v_numeric"),
                right: "v_numeric",
                dsl: dsl::numeric_numeric,
            },
            Pair {
                left: Some("v_path"),
                right: "v_point",
                dsl: dsl::path_point,
            },
            Pair {
                left: Some("v_point"),
                right: "v_point",
                dsl: dsl::point_point,
            },
        ],
    );
}
