// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::fact as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "!!",
        &[Pair {
            left: None,
            right: "v_tsquery",
            dsl: dsl::tsquery,
        }],
    );
}
