// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::intersects as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "?#",
        &[
            Pair {
                left: Some("v_box"),
                right: "v_box",
                dsl: dsl::box_box,
            },
            Pair {
                left: Some("v_line"),
                right: "v_box",
                dsl: dsl::line_box,
            },
            Pair {
                left: Some("v_line"),
                right: "v_line",
                dsl: dsl::line_line,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_box",
                dsl: dsl::lseg_box,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_line",
                dsl: dsl::lseg_line,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_lseg",
                dsl: dsl::lseg_lseg,
            },
            Pair {
                left: Some("v_path"),
                right: "v_path",
                dsl: dsl::path_path,
            },
        ],
    );
}
