// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::json_get_text as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "->>",
        &[
            Pair {
                left: Some("v_json"),
                right: "v_int4",
                dsl: dsl::json_int4,
            },
            Pair {
                left: Some("v_json"),
                right: "v_text",
                dsl: dsl::json_text,
            },
            Pair {
                left: Some("v_jsonb"),
                right: "v_int4",
                dsl: dsl::jsonb_int4,
            },
            Pair {
                left: Some("v_jsonb"),
                right: "v_text",
                dsl: dsl::jsonb_text,
            },
        ],
    );
}
