// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::json_exists_any as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "?|",
        &[
            Pair {
                left: Some("v_jsonb"),
                right: "v_text_array",
                dsl: dsl::jsonb_text_array,
            },
            Pair {
                left: None,
                right: "v_line",
                dsl: dsl::line,
            },
            Pair {
                left: None,
                right: "v_lseg",
                dsl: dsl::lseg,
            },
            Pair {
                left: Some("v_point"),
                right: "v_point",
                dsl: dsl::point_point,
            },
        ],
    );
}
