// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::length as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "@-@",
        &[
            Pair {
                left: None,
                right: "v_lseg",
                dsl: dsl::lseg,
            },
            Pair {
                left: None,
                right: "v_path",
                dsl: dsl::path,
            },
        ],
    );
}
