// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::lt as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "<",
        &[
            Pair {
                left: Some("v_bit"),
                right: "v_bit",
                dsl: dsl::bit_bit,
            },
            Pair {
                left: Some("v_bool"),
                right: "v_bool",
                dsl: dsl::bool_bool,
            },
            Pair {
                left: Some("v_box"),
                right: "v_box",
                dsl: dsl::box_box,
            },
            Pair {
                left: Some("v_bpchar"),
                right: "v_bpchar",
                dsl: dsl::bpchar_bpchar,
            },
            Pair {
                left: Some("v_bytea"),
                right: "v_bytea",
                dsl: dsl::bytea_bytea,
            },
            Pair {
                left: Some("v_char"),
                right: "v_char",
                dsl: dsl::char_char,
            },
            Pair {
                left: Some("v_circle"),
                right: "v_circle",
                dsl: dsl::circle_circle,
            },
            Pair {
                left: Some("v_date"),
                right: "v_date",
                dsl: dsl::date_date,
            },
            Pair {
                left: Some("v_date"),
                right: "v_timestamp",
                dsl: dsl::date_timestamp,
            },
            Pair {
                left: Some("v_date"),
                right: "v_timestamptz",
                dsl: dsl::date_timestamptz,
            },
            Pair {
                left: Some("v_float4"),
                right: "v_float4",
                dsl: dsl::float4_float4,
            },
            Pair {
                left: Some("v_float4"),
                right: "v_float8",
                dsl: dsl::float4_float8,
            },
            Pair {
                left: Some("v_float8"),
                right: "v_float4",
                dsl: dsl::float8_float4,
            },
            Pair {
                left: Some("v_float8"),
                right: "v_float8",
                dsl: dsl::float8_float8,
            },
            Pair {
                left: Some("v_inet"),
                right: "v_inet",
                dsl: dsl::inet_inet,
            },
            Pair {
                left: Some("v_int2"),
                right: "v_int2",
                dsl: dsl::int2_int2,
            },
            Pair {
                left: Some("v_int2"),
                right: "v_int4",
                dsl: dsl::int2_int4,
            },
            Pair {
                left: Some("v_int2"),
                right: "v_int8",
                dsl: dsl::int2_int8,
            },
            Pair {
                left: Some("v_int4_array"),
                right: "v_int4_array",
                dsl: dsl::int4_array_int4_array,
            },
            Pair {
                left: Some("v_int4"),
                right: "v_int2",
                dsl: dsl::int4_int2,
            },
            Pair {
                left: Some("v_int4"),
                right: "v_int4",
                dsl: dsl::int4_int4,
            },
            Pair {
                left: Some("v_int4"),
                right: "v_int8",
                dsl: dsl::int4_int8,
            },
            Pair {
                left: Some("v_int4multirange"),
                right: "v_int4multirange",
                dsl: dsl::int4multirange_int4multirange,
            },
            Pair {
                left: Some("v_int4range"),
                right: "v_int4range",
                dsl: dsl::int4range_int4range,
            },
            Pair {
                left: Some("v_int8"),
                right: "v_int2",
                dsl: dsl::int8_int2,
            },
            Pair {
                left: Some("v_int8"),
                right: "v_int4",
                dsl: dsl::int8_int4,
            },
            Pair {
                left: Some("v_int8"),
                right: "v_int8",
                dsl: dsl::int8_int8,
            },
            Pair {
                left: Some("v_interval"),
                right: "v_interval",
                dsl: dsl::interval_interval,
            },
            Pair {
                left: Some("v_jsonb"),
                right: "v_jsonb",
                dsl: dsl::jsonb_jsonb,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_lseg",
                dsl: dsl::lseg_lseg,
            },
            Pair {
                left: Some("v_macaddr8"),
                right: "v_macaddr8",
                dsl: dsl::macaddr8_macaddr8,
            },
            Pair {
                left: Some("v_macaddr"),
                right: "v_macaddr",
                dsl: dsl::macaddr_macaddr,
            },
            Pair {
                left: Some("v_money"),
                right: "v_money",
                dsl: dsl::money_money,
            },
            Pair {
                left: Some("v_mood"),
                right: "v_mood",
                dsl: dsl::mood_mood,
            },
            Pair {
                left: Some("v_numeric"),
                right: "v_numeric",
                dsl: dsl::numeric_numeric,
            },
            Pair {
                left: Some("v_path"),
                right: "v_path",
                dsl: dsl::path_path,
            },
            Pair {
                left: Some("v_price_tag"),
                right: "v_price_tag",
                dsl: dsl::price_tag_price_tag,
            },
            Pair {
                left: Some("v_text_array"),
                right: "v_text_array",
                dsl: dsl::text_array_text_array,
            },
            Pair {
                left: Some("v_text"),
                right: "v_text",
                dsl: dsl::text_text,
            },
            Pair {
                left: Some("v_time"),
                right: "v_time",
                dsl: dsl::time_time,
            },
            Pair {
                left: Some("v_timestamp"),
                right: "v_date",
                dsl: dsl::timestamp_date,
            },
            Pair {
                left: Some("v_timestamp"),
                right: "v_timestamp",
                dsl: dsl::timestamp_timestamp,
            },
            Pair {
                left: Some("v_timestamp"),
                right: "v_timestamptz",
                dsl: dsl::timestamp_timestamptz,
            },
            Pair {
                left: Some("v_timestamptz"),
                right: "v_date",
                dsl: dsl::timestamptz_date,
            },
            Pair {
                left: Some("v_timestamptz"),
                right: "v_timestamp",
                dsl: dsl::timestamptz_timestamp,
            },
            Pair {
                left: Some("v_timestamptz"),
                right: "v_timestamptz",
                dsl: dsl::timestamptz_timestamptz,
            },
            Pair {
                left: Some("v_timetz"),
                right: "v_timetz",
                dsl: dsl::timetz_timetz,
            },
            Pair {
                left: Some("v_tsquery"),
                right: "v_tsquery",
                dsl: dsl::tsquery_tsquery,
            },
            Pair {
                left: Some("v_tsrange"),
                right: "v_tsrange",
                dsl: dsl::tsrange_tsrange,
            },
            Pair {
                left: Some("v_tsvector"),
                right: "v_tsvector",
                dsl: dsl::tsvector_tsvector,
            },
            Pair {
                left: Some("v_uuid"),
                right: "v_uuid",
                dsl: dsl::uuid_uuid,
            },
            Pair {
                left: Some("v_varbit"),
                right: "v_varbit",
                dsl: dsl::varbit_varbit,
            },
        ],
    );
}
