// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::matches as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "@@",
        &[
            Pair {
                left: None,
                right: "v_circle",
                dsl: dsl::circle,
            },
            Pair {
                left: Some("v_jsonb"),
                right: "v_jsonpath",
                dsl: dsl::jsonb_jsonpath,
            },
            Pair {
                left: None,
                right: "v_lseg",
                dsl: dsl::lseg,
            },
            Pair {
                left: None,
                right: "v_polygon",
                dsl: dsl::polygon,
            },
            Pair {
                left: None,
                right: "v_box",
                dsl: dsl::r#box,
            },
            Pair {
                left: Some("v_text"),
                right: "v_text",
                dsl: dsl::text_text,
            },
            Pair {
                left: Some("v_text"),
                right: "v_tsquery",
                dsl: dsl::text_tsquery,
            },
            Pair {
                left: Some("v_tsquery"),
                right: "v_tsvector",
                dsl: dsl::tsquery_tsvector,
            },
            Pair {
                left: Some("v_tsvector"),
                right: "v_tsquery",
                dsl: dsl::tsvector_tsquery,
            },
        ],
    );
}
