// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::minus as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "-",
        &[
            Pair {
                left: Some("v_box"),
                right: "v_point",
                dsl: dsl::box_point,
            },
            Pair {
                left: Some("v_circle"),
                right: "v_point",
                dsl: dsl::circle_point,
            },
            Pair {
                left: Some("v_date"),
                right: "v_date",
                dsl: dsl::date_date,
            },
            Pair {
                left: Some("v_date"),
                right: "v_int4",
                dsl: dsl::date_int4,
            },
            Pair {
                left: Some("v_date"),
                right: "v_interval",
                dsl: dsl::date_interval,
            },
            Pair {
                left: None,
                right: "v_float4",
                dsl: dsl::float4,
            },
            Pair {
                left: Some("v_float4"),
                right: "v_float4",
                dsl: dsl::float4_float4,
            },
            Pair {
                left: Some("v_float4"),
                right: "v_float8",
                dsl: dsl::float4_float8,
            },
            Pair {
                left: None,
                right: "v_float8",
                dsl: dsl::float8,
            },
            Pair {
                left: Some("v_float8"),
                right: "v_float4",
                dsl: dsl::float8_float4,
            },
            Pair {
                left: Some("v_float8"),
                right: "v_float8",
                dsl: dsl::float8_float8,
            },
            Pair {
                left: Some("v_inet"),
                right: "v_inet",
                dsl: dsl::inet_inet,
            },
            Pair {
                left: Some("v_inet"),
                right: "v_int8",
                dsl: dsl::inet_int8,
            },
            Pair {
                left: None,
                right: "v_int2",
                dsl: dsl::int2,
            },
            Pair {
                left: Some("v_int2"),
                right: "v_int2",
                dsl: dsl::int2_int2,
            },
            Pair {
                left: Some("v_int2"),
                right: "v_int4",
                dsl: dsl::int2_int4,
            },
            Pair {
                left: Some("v_int2"),
                right: "v_int8",
                dsl: dsl::int2_int8,
            },
            Pair {
                left: None,
                right: "v_int4",
                dsl: dsl::int4,
            },
            Pair {
                left: Some("v_int4"),
                right: "v_int2",
                dsl: dsl::int4_int2,
            },
            Pair {
                left: Some("v_int4"),
                right: "v_int4",
                dsl: dsl::int4_int4,
            },
            Pair {
                left: Some("v_int4"),
                right: "v_int8",
                dsl: dsl::int4_int8,
            },
            Pair {
                left: Some("v_int4multirange"),
                right: "v_int4multirange",
                dsl: dsl::int4multirange_int4multirange,
            },
            Pair {
                left: Some("v_int4range"),
                right: "v_int4range",
                dsl: dsl::int4range_int4range,
            },
            Pair {
                left: None,
                right: "v_int8",
                dsl: dsl::int8,
            },
            Pair {
                left: Some("v_int8"),
                right: "v_int2",
                dsl: dsl::int8_int2,
            },
            Pair {
                left: Some("v_int8"),
                right: "v_int4",
                dsl: dsl::int8_int4,
            },
            Pair {
                left: Some("v_int8"),
                right: "v_int8",
                dsl: dsl::int8_int8,
            },
            Pair {
                left: None,
                right: "v_interval",
                dsl: dsl::interval,
            },
            Pair {
                left: Some("v_interval"),
                right: "v_interval",
                dsl: dsl::interval_interval,
            },
            Pair {
                left: Some("v_jsonb"),
                right: "v_int4",
                dsl: dsl::jsonb_int4,
            },
            Pair {
                left: Some("v_jsonb"),
                right: "v_text",
                dsl: dsl::jsonb_text,
            },
            Pair {
                left: Some("v_jsonb"),
                right: "v_text_array",
                dsl: dsl::jsonb_text_array,
            },
            Pair {
                left: Some("v_money"),
                right: "v_money",
                dsl: dsl::money_money,
            },
            Pair {
                left: None,
                right: "v_numeric",
                dsl: dsl::numeric,
            },
            Pair {
                left: Some("v_numeric"),
                right: "v_numeric",
                dsl: dsl::numeric_numeric,
            },
            Pair {
                left: Some("v_path"),
                right: "v_point",
                dsl: dsl::path_point,
            },
            Pair {
                left: Some("v_point"),
                right: "v_point",
                dsl: dsl::point_point,
            },
            Pair {
                left: Some("v_time"),
                right: "v_interval",
                dsl: dsl::time_interval,
            },
            Pair {
                left: Some("v_time"),
                right: "v_time",
                dsl: dsl::time_time,
            },
            Pair {
                left: Some("v_timestamp"),
                right: "v_interval",
                dsl: dsl::timestamp_interval,
            },
            Pair {
                left: Some("v_timestamp"),
                right: "v_timestamp",
                dsl: dsl::timestamp_timestamp,
            },
            Pair {
                left: Some("v_timestamptz"),
                right: "v_interval",
                dsl: dsl::timestamptz_interval,
            },
            Pair {
                left: Some("v_timestamptz"),
                right: "v_timestamptz",
                dsl: dsl::timestamptz_timestamptz,
            },
            Pair {
                left: Some("v_timetz"),
                right: "v_interval",
                dsl: dsl::timetz_interval,
            },
            Pair {
                left: Some("v_tsrange"),
                right: "v_tsrange",
                dsl: dsl::tsrange_tsrange,
            },
        ],
    );
}
