// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::not_like as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "!~~",
        &[
            Pair {
                left: Some("v_bpchar"),
                right: "v_text",
                dsl: dsl::bpchar_text,
            },
            Pair {
                left: Some("v_bytea"),
                right: "v_bytea",
                dsl: dsl::bytea_bytea,
            },
            Pair {
                left: Some("v_text"),
                right: "v_text",
                dsl: dsl::text_text,
            },
        ],
    );
}
