// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::overleft as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "&<",
        &[
            Pair {
                left: Some("v_box"),
                right: "v_box",
                dsl: dsl::box_box,
            },
            Pair {
                left: Some("v_circle"),
                right: "v_circle",
                dsl: dsl::circle_circle,
            },
            Pair {
                left: Some("v_int4multirange"),
                right: "v_int4multirange",
                dsl: dsl::int4multirange_int4multirange,
            },
            Pair {
                left: Some("v_int4multirange"),
                right: "v_int4range",
                dsl: dsl::int4multirange_int4range,
            },
            Pair {
                left: Some("v_int4range"),
                right: "v_int4multirange",
                dsl: dsl::int4range_int4multirange,
            },
            Pair {
                left: Some("v_int4range"),
                right: "v_int4range",
                dsl: dsl::int4range_int4range,
            },
            Pair {
                left: Some("v_polygon"),
                right: "v_polygon",
                dsl: dsl::polygon_polygon,
            },
            Pair {
                left: Some("v_tsrange"),
                right: "v_tsrange",
                dsl: dsl::tsrange_tsrange,
            },
        ],
    );
}
