// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::perpendicular as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "?-|",
        &[
            Pair {
                left: Some("v_line"),
                right: "v_line",
                dsl: dsl::line_line,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_lseg",
                dsl: dsl::lseg_lseg,
            },
        ],
    );
}
