// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::pow as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "^",
        &[
            Pair {
                left: Some("v_float8"),
                right: "v_float8",
                dsl: dsl::float8_float8,
            },
            Pair {
                left: Some("v_numeric"),
                right: "v_numeric",
                dsl: dsl::numeric_numeric,
            },
        ],
    );
}
