// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::rec_ge as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "*>=",
        &[Pair {
            left: Some("v_price_tag"),
            right: "v_price_tag",
            dsl: dsl::price_tag_price_tag,
        }],
    );
}
