// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::regex as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "~",
        &[
            Pair {
                left: None,
                right: "v_bit",
                dsl: dsl::bit,
            },
            Pair {
                left: Some("v_bpchar"),
                right: "v_text",
                dsl: dsl::bpchar_text,
            },
            Pair {
                left: None,
                right: "v_inet",
                dsl: dsl::inet,
            },
            Pair {
                left: None,
                right: "v_int2",
                dsl: dsl::int2,
            },
            Pair {
                left: None,
                right: "v_int4",
                dsl: dsl::int4,
            },
            Pair {
                left: None,
                right: "v_int8",
                dsl: dsl::int8,
            },
            Pair {
                left: None,
                right: "v_macaddr",
                dsl: dsl::macaddr,
            },
            Pair {
                left: None,
                right: "v_macaddr8",
                dsl: dsl::macaddr8,
            },
            Pair {
                left: Some("v_text"),
                right: "v_text",
                dsl: dsl::text_text,
            },
        ],
    );
}
