// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::same_as as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "~=",
        &[
            Pair {
                left: Some("v_box"),
                right: "v_box",
                dsl: dsl::box_box,
            },
            Pair {
                left: Some("v_circle"),
                right: "v_circle",
                dsl: dsl::circle_circle,
            },
            Pair {
                left: Some("v_point"),
                right: "v_point",
                dsl: dsl::point_point,
            },
            Pair {
                left: Some("v_polygon"),
                right: "v_polygon",
                dsl: dsl::polygon_polygon,
            },
        ],
    );
}
