// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::starts_with as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "^@",
        &[Pair {
            left: Some("v_text"),
            right: "v_text",
            dsl: dsl::text_text,
        }],
    );
}
