// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::subnet_le as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "<<=",
        &[Pair {
            left: Some("v_inet"),
            right: "v_inet",
            dsl: dsl::inet_inet,
        }],
    );
}
