// Generated by `cargo run -p opgen` from PostgreSQL 18.6 (Debian 18.6-1.pgdg13+2). Do not edit.

use super::super::dsl::xor as dsl;
use super::super::{Pair, run};

#[test]
fn all() {
    run(
        "#",
        &[
            Pair {
                left: Some("v_bit"),
                right: "v_bit",
                dsl: dsl::bit_bit,
            },
            Pair {
                left: Some("v_box"),
                right: "v_box",
                dsl: dsl::box_box,
            },
            Pair {
                left: Some("v_int2"),
                right: "v_int2",
                dsl: dsl::int2_int2,
            },
            Pair {
                left: Some("v_int4"),
                right: "v_int4",
                dsl: dsl::int4_int4,
            },
            Pair {
                left: Some("v_int8"),
                right: "v_int8",
                dsl: dsl::int8_int8,
            },
            Pair {
                left: Some("v_line"),
                right: "v_line",
                dsl: dsl::line_line,
            },
            Pair {
                left: Some("v_lseg"),
                right: "v_lseg",
                dsl: dsl::lseg_lseg,
            },
            Pair {
                left: None,
                right: "v_path",
                dsl: dsl::path,
            },
            Pair {
                left: None,
                right: "v_polygon",
                dsl: dsl::polygon,
            },
        ],
    );
}
