//! Generated by `cargo run -p schemagen` from PostgreSQL 18.6. Do not edit.

#![allow(non_upper_case_globals)]

use surus::*;

surus::sql_enum!(Mood = "mood");
surus::domain!(PositiveInt = "positive_int": Int4);
surus::composite!(PriceTag = "price_tag", PriceTagFields {
    amount: "amount" Numeric;
    currency: "currency" Text;
});

surus::table!(order: Order(OrderTable) = "public"."Order" {
    id: "Id" Int8, NotNull;
    user: "user" Text, NotNull;
    select: "select" Int4, NotNull;
    line_total: "line total" Numeric, Nullable;
});
pub const order_pkey: Constraint<OrderTable> = Constraint::new("Order_pkey");

surus::table!(grouped_users: GroupedUsers(GroupedUsersTable) = "public"."grouped_users" {
    id: "id" Int8, Nullable;
    name: "name" Text, Nullable;
    email: "email" Text, Nullable;
    group_id: "group_id" Int8, Nullable;
});

surus::table!(groups: Groups(GroupsTable) = "public"."groups" {
    id: "id" Int8, NotNull;
    name: "name" Text, NotNull;
    parent_id: "parent_id" Int8, Nullable;
});
pub const groups_pkey: Constraint<GroupsTable> = Constraint::new("groups_pkey");

surus::table!(logins_day_01: LoginsDay01(LoginsDay01Table) = "public"."logins_day_01" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_01_pkey: Constraint<LoginsDay01Table> = Constraint::new("logins_day_01_pkey");

surus::table!(logins_day_02: LoginsDay02(LoginsDay02Table) = "public"."logins_day_02" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_02_pkey: Constraint<LoginsDay02Table> = Constraint::new("logins_day_02_pkey");

surus::table!(logins_day_03: LoginsDay03(LoginsDay03Table) = "public"."logins_day_03" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_03_pkey: Constraint<LoginsDay03Table> = Constraint::new("logins_day_03_pkey");

surus::table!(logins_day_04: LoginsDay04(LoginsDay04Table) = "public"."logins_day_04" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_04_pkey: Constraint<LoginsDay04Table> = Constraint::new("logins_day_04_pkey");

surus::table!(logins_day_05: LoginsDay05(LoginsDay05Table) = "public"."logins_day_05" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_05_pkey: Constraint<LoginsDay05Table> = Constraint::new("logins_day_05_pkey");

surus::table!(logins_day_06: LoginsDay06(LoginsDay06Table) = "public"."logins_day_06" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_06_pkey: Constraint<LoginsDay06Table> = Constraint::new("logins_day_06_pkey");

surus::table!(logins_day_07: LoginsDay07(LoginsDay07Table) = "public"."logins_day_07" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_07_pkey: Constraint<LoginsDay07Table> = Constraint::new("logins_day_07_pkey");

surus::table!(logins_day_08: LoginsDay08(LoginsDay08Table) = "public"."logins_day_08" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_08_pkey: Constraint<LoginsDay08Table> = Constraint::new("logins_day_08_pkey");

surus::table!(logins_day_09: LoginsDay09(LoginsDay09Table) = "public"."logins_day_09" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_09_pkey: Constraint<LoginsDay09Table> = Constraint::new("logins_day_09_pkey");

surus::table!(logins_day_10: LoginsDay10(LoginsDay10Table) = "public"."logins_day_10" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_10_pkey: Constraint<LoginsDay10Table> = Constraint::new("logins_day_10_pkey");

surus::table!(logins_day_11: LoginsDay11(LoginsDay11Table) = "public"."logins_day_11" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_11_pkey: Constraint<LoginsDay11Table> = Constraint::new("logins_day_11_pkey");

surus::table!(logins_day_12: LoginsDay12(LoginsDay12Table) = "public"."logins_day_12" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_12_pkey: Constraint<LoginsDay12Table> = Constraint::new("logins_day_12_pkey");

surus::table!(logins_day_13: LoginsDay13(LoginsDay13Table) = "public"."logins_day_13" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_13_pkey: Constraint<LoginsDay13Table> = Constraint::new("logins_day_13_pkey");

surus::table!(logins_day_14: LoginsDay14(LoginsDay14Table) = "public"."logins_day_14" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_14_pkey: Constraint<LoginsDay14Table> = Constraint::new("logins_day_14_pkey");

surus::table!(logins_day_15: LoginsDay15(LoginsDay15Table) = "public"."logins_day_15" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_15_pkey: Constraint<LoginsDay15Table> = Constraint::new("logins_day_15_pkey");

surus::table!(logins_day_16: LoginsDay16(LoginsDay16Table) = "public"."logins_day_16" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_16_pkey: Constraint<LoginsDay16Table> = Constraint::new("logins_day_16_pkey");

surus::table!(logins_day_17: LoginsDay17(LoginsDay17Table) = "public"."logins_day_17" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_17_pkey: Constraint<LoginsDay17Table> = Constraint::new("logins_day_17_pkey");

surus::table!(logins_day_18: LoginsDay18(LoginsDay18Table) = "public"."logins_day_18" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_18_pkey: Constraint<LoginsDay18Table> = Constraint::new("logins_day_18_pkey");

surus::table!(logins_day_19: LoginsDay19(LoginsDay19Table) = "public"."logins_day_19" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_19_pkey: Constraint<LoginsDay19Table> = Constraint::new("logins_day_19_pkey");

surus::table!(logins_day_20: LoginsDay20(LoginsDay20Table) = "public"."logins_day_20" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_20_pkey: Constraint<LoginsDay20Table> = Constraint::new("logins_day_20_pkey");

surus::table!(logins_day_21: LoginsDay21(LoginsDay21Table) = "public"."logins_day_21" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_21_pkey: Constraint<LoginsDay21Table> = Constraint::new("logins_day_21_pkey");

surus::table!(logins_day_22: LoginsDay22(LoginsDay22Table) = "public"."logins_day_22" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_22_pkey: Constraint<LoginsDay22Table> = Constraint::new("logins_day_22_pkey");

surus::table!(logins_day_23: LoginsDay23(LoginsDay23Table) = "public"."logins_day_23" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_23_pkey: Constraint<LoginsDay23Table> = Constraint::new("logins_day_23_pkey");

surus::table!(logins_day_24: LoginsDay24(LoginsDay24Table) = "public"."logins_day_24" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_24_pkey: Constraint<LoginsDay24Table> = Constraint::new("logins_day_24_pkey");

surus::table!(logins_day_25: LoginsDay25(LoginsDay25Table) = "public"."logins_day_25" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_25_pkey: Constraint<LoginsDay25Table> = Constraint::new("logins_day_25_pkey");

surus::table!(logins_day_26: LoginsDay26(LoginsDay26Table) = "public"."logins_day_26" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_26_pkey: Constraint<LoginsDay26Table> = Constraint::new("logins_day_26_pkey");

surus::table!(logins_day_27: LoginsDay27(LoginsDay27Table) = "public"."logins_day_27" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_27_pkey: Constraint<LoginsDay27Table> = Constraint::new("logins_day_27_pkey");

surus::table!(logins_day_28: LoginsDay28(LoginsDay28Table) = "public"."logins_day_28" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_28_pkey: Constraint<LoginsDay28Table> = Constraint::new("logins_day_28_pkey");

surus::table!(logins_day_29: LoginsDay29(LoginsDay29Table) = "public"."logins_day_29" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_29_pkey: Constraint<LoginsDay29Table> = Constraint::new("logins_day_29_pkey");

surus::table!(logins_day_30: LoginsDay30(LoginsDay30Table) = "public"."logins_day_30" {
    user_id: "user_id" Int8, NotNull;
    logins: "logins" Int4, NotNull;
});
pub const logins_day_30_pkey: Constraint<LoginsDay30Table> = Constraint::new("logins_day_30_pkey");

surus::table!(products: Products(ProductsTable) = "public"."products" {
    id: "id" Int8, NotNull;
    name: "name" Text, NotNull;
    price_cents: "price_cents" Int4, NotNull;
    quantity: "quantity" Int4, NotNull;
    total_cents: "total_cents" Int8, Nullable;
    price_with_tax: "price_with_tax" Int8, Nullable;
});
pub const products_pkey: Constraint<ProductsTable> = Constraint::new("products_pkey");

surus::table!(reservations: Reservations(ReservationsTable) = "public"."reservations" {
    room: "room" Int4, NotNull;
    during: "during" Range<Timestamp>, NotNull;
});
pub const reservations_pkey: Constraint<ReservationsTable> = Constraint::new("reservations_pkey");

surus::table!(tickets: Tickets(TicketsTable) = "public"."tickets" {
    id: "id" Int8, NotNull;
    batch: "batch" Text, NotNull;
    name: "name" Text, NotNull;
});
pub const tickets_batch_name_key: Constraint<TicketsTable> =
    Constraint::new("tickets_batch_name_key");
pub const tickets_pkey: Constraint<TicketsTable> = Constraint::new("tickets_pkey");

surus::table!(type_samples: TypeSamples(TypeSamplesTable) = "public"."type_samples" {
    v_bool: "v_bool" Bool, Nullable;
    v_int2: "v_int2" Int2, Nullable;
    v_int4: "v_int4" Int4, Nullable;
    v_int8: "v_int8" Int8, Nullable;
    v_numeric: "v_numeric" Numeric, Nullable;
    v_float4: "v_float4" Float4, Nullable;
    v_float8: "v_float8" Float8, Nullable;
    v_money: "v_money" Money, Nullable;
    v_text: "v_text" Text, Nullable;
    v_varchar: "v_varchar" Varchar, Nullable;
    v_bpchar: "v_bpchar" Bpchar, Nullable;
    v_char: "v_char" Char, Nullable;
    v_date: "v_date" Date, Nullable;
    v_time: "v_time" Time, Nullable;
    v_timetz: "v_timetz" Timetz, Nullable;
    v_timestamp: "v_timestamp" Timestamp, Nullable;
    v_timestamptz: "v_timestamptz" Timestamptz, Nullable;
    v_interval: "v_interval" Interval, Nullable;
    v_bytea: "v_bytea" Bytea, Nullable;
    v_uuid: "v_uuid" Uuid, Nullable;
    v_json: "v_json" Json, Nullable;
    v_jsonb: "v_jsonb" Jsonb, Nullable;
    v_jsonpath: "v_jsonpath" Jsonpath, Nullable;
    v_inet: "v_inet" Inet, Nullable;
    v_cidr: "v_cidr" Cidr, Nullable;
    v_macaddr: "v_macaddr" Macaddr, Nullable;
    v_macaddr8: "v_macaddr8" Macaddr8, Nullable;
    v_bit: "v_bit" Bit, Nullable;
    v_varbit: "v_varbit" Varbit, Nullable;
    v_point: "v_point" Point, Nullable;
    v_line: "v_line" Line, Nullable;
    v_lseg: "v_lseg" Lseg, Nullable;
    v_box: "v_box" PgBox, Nullable;
    v_circle: "v_circle" Circle, Nullable;
    v_path: "v_path" Path, Nullable;
    v_polygon: "v_polygon" Polygon, Nullable;
    v_tsvector: "v_tsvector" Tsvector, Nullable;
    v_tsquery: "v_tsquery" Tsquery, Nullable;
    v_xml: "v_xml" Xml, Nullable;
    v_int4_array: "v_int4_array" Array<Int4>, Nullable;
    v_text_array: "v_text_array" Array<Text>, Nullable;
    v_int4range: "v_int4range" Range<Int4>, Nullable;
    v_tsrange: "v_tsrange" Range<Timestamp>, Nullable;
    v_int4multirange: "v_int4multirange" Multirange<Int4>, Nullable;
    v_mood: "v_mood" Mood, Nullable;
    v_positive_int: "v_positive_int" PositiveInt, Nullable;
    v_price_tag: "v_price_tag" PriceTag, Nullable;
});

surus::table!(user_profiles: UserProfiles(UserProfilesTable) = "public"."user_profiles" {
    user_id: "user_id" Int8, NotNull;
    bio: "bio" Text, NotNull;
});
pub const user_profiles_pkey: Constraint<UserProfilesTable> = Constraint::new("user_profiles_pkey");

surus::table!(user_settings: UserSettings(UserSettingsTable) = "public"."user_settings" {
    user_id: "user_id" Int8, NotNull;
    theme: "theme" Text, NotNull;
});
pub const user_settings_pkey: Constraint<UserSettingsTable> = Constraint::new("user_settings_pkey");

surus::table!(users: Users(UsersTable) = "public"."users" {
    id: "id" Int8, NotNull;
    name: "name" Text, NotNull;
    email: "email" Text, Nullable;
    group_id: "group_id" Int8, Nullable;
});
pub const users_pkey: Constraint<UsersTable> = Constraint::new("users_pkey");

surus::table!(users_with_groups: UsersWithGroups(UsersWithGroupsTable) = "public"."users_with_groups" {
    id: "id" Int8, Nullable;
    name: "name" Text, Nullable;
    group_name: "group_name" Text, Nullable;
});

pub mod app {
    use surus::*;

    surus::table!(users: Users(UsersTable) = "app"."users" {
        id: "id" Int8, NotNull;
        name: "name" Text, NotNull;
    });
    pub const users_pkey: Constraint<UsersTable> = Constraint::new("users_pkey");
}

surus::binary_operators! {
    BitAnd: Int2, PositiveInt => Int4;
    BitAnd: Int4, PositiveInt => Int4;
    BitAnd: Int8, PositiveInt => Int8;
    BitAnd: PositiveInt, Int2 => Int4;
    BitAnd: PositiveInt, Int4 => Int4;
    BitAnd: PositiveInt, Int8 => Int8;
    BitAnd: PositiveInt, PositiveInt => Int4;
    BitOr: Int2, PositiveInt => Int4;
    BitOr: Int4, PositiveInt => Int4;
    BitOr: Int8, PositiveInt => Int8;
    BitOr: PositiveInt, Int2 => Int4;
    BitOr: PositiveInt, Int4 => Int4;
    BitOr: PositiveInt, Int8 => Int8;
    BitOr: PositiveInt, PositiveInt => Int4;
    Concat: Array<Int4>, PositiveInt => Array<Int4>;
    Concat: Bpchar, Mood => Text;
    Concat: Bpchar, PositiveInt => Text;
    Concat: Bpchar, PriceTag => Text;
    Concat: Char, Mood => Text;
    Concat: Char, PositiveInt => Text;
    Concat: Char, PriceTag => Text;
    Concat: Mood, Bpchar => Text;
    Concat: Mood, Char => Text;
    Concat: Mood, Text => Text;
    Concat: Mood, Varchar => Text;
    Concat: PositiveInt, Array<Int4> => Array<Int4>;
    Concat: PositiveInt, Bpchar => Text;
    Concat: PositiveInt, Char => Text;
    Concat: PositiveInt, Text => Text;
    Concat: PositiveInt, Varchar => Text;
    Concat: PriceTag, Bpchar => Text;
    Concat: PriceTag, Char => Text;
    Concat: PriceTag, Text => Text;
    Concat: PriceTag, Varchar => Text;
    Concat: Text, Mood => Text;
    Concat: Text, PositiveInt => Text;
    Concat: Text, PriceTag => Text;
    Concat: Varchar, Mood => Text;
    Concat: Varchar, PositiveInt => Text;
    Concat: Varchar, PriceTag => Text;
    Distance: Float4, PositiveInt => Float4;
    Distance: Float8, PositiveInt => Float8;
    Distance: Int2, PositiveInt => Int4;
    Distance: Int4, PositiveInt => Int4;
    Distance: Int8, PositiveInt => Int8;
    Distance: Numeric, PositiveInt => Float8;
    Distance: PositiveInt, Float4 => Float4;
    Distance: PositiveInt, Float8 => Float8;
    Distance: PositiveInt, Int2 => Int4;
    Distance: PositiveInt, Int4 => Int4;
    Distance: PositiveInt, Int8 => Int8;
    Distance: PositiveInt, Numeric => Float8;
    Distance: PositiveInt, PositiveInt => Int4;
    Div: Float4, PositiveInt => Float8;
    Div: Float8, PositiveInt => Float8;
    Div: Int2, PositiveInt => Int4;
    Div: Int4, PositiveInt => Int4;
    Div: Int8, PositiveInt => Int8;
    Div: Interval, PositiveInt => Interval;
    Div: Money, PositiveInt => Money;
    Div: Numeric, PositiveInt => Numeric;
    Div: PositiveInt, Float4 => Float8;
    Div: PositiveInt, Float8 => Float8;
    Div: PositiveInt, Int2 => Int4;
    Div: PositiveInt, Int4 => Int4;
    Div: PositiveInt, Int8 => Int8;
    Div: PositiveInt, Numeric => Numeric;
    Div: PositiveInt, PositiveInt => Int4;
    Div: Time, PositiveInt => Interval;
    Eq: Float4, PositiveInt => Bool;
    Eq: Float8, PositiveInt => Bool;
    Eq: Int2, PositiveInt => Bool;
    Eq: Int4, PositiveInt => Bool;
    Eq: Int8, PositiveInt => Bool;
    Eq: Mood, Mood => Bool;
    Eq: Numeric, PositiveInt => Bool;
    Eq: PositiveInt, Float4 => Bool;
    Eq: PositiveInt, Float8 => Bool;
    Eq: PositiveInt, Int2 => Bool;
    Eq: PositiveInt, Int4 => Bool;
    Eq: PositiveInt, Int8 => Bool;
    Eq: PositiveInt, Numeric => Bool;
    Eq: PositiveInt, PositiveInt => Bool;
    Eq: PriceTag, PriceTag => Bool;
    Ge: Float4, PositiveInt => Bool;
    Ge: Float8, PositiveInt => Bool;
    Ge: Int2, PositiveInt => Bool;
    Ge: Int4, PositiveInt => Bool;
    Ge: Int8, PositiveInt => Bool;
    Ge: Mood, Mood => Bool;
    Ge: Numeric, PositiveInt => Bool;
    Ge: PositiveInt, Float4 => Bool;
    Ge: PositiveInt, Float8 => Bool;
    Ge: PositiveInt, Int2 => Bool;
    Ge: PositiveInt, Int4 => Bool;
    Ge: PositiveInt, Int8 => Bool;
    Ge: PositiveInt, Numeric => Bool;
    Ge: PositiveInt, PositiveInt => Bool;
    Ge: PriceTag, PriceTag => Bool;
    Get: Json, PositiveInt => Json;
    Get: Jsonb, PositiveInt => Jsonb;
    GetText: Json, PositiveInt => Text;
    GetText: Jsonb, PositiveInt => Text;
    Gt: Float4, PositiveInt => Bool;
    Gt: Float8, PositiveInt => Bool;
    Gt: Int2, PositiveInt => Bool;
    Gt: Int4, PositiveInt => Bool;
    Gt: Int8, PositiveInt => Bool;
    Gt: Mood, Mood => Bool;
    Gt: Numeric, PositiveInt => Bool;
    Gt: PositiveInt, Float4 => Bool;
    Gt: PositiveInt, Float8 => Bool;
    Gt: PositiveInt, Int2 => Bool;
    Gt: PositiveInt, Int4 => Bool;
    Gt: PositiveInt, Int8 => Bool;
    Gt: PositiveInt, Numeric => Bool;
    Gt: PositiveInt, PositiveInt => Bool;
    Gt: PriceTag, PriceTag => Bool;
    Le: Float4, PositiveInt => Bool;
    Le: Float8, PositiveInt => Bool;
    Le: Int2, PositiveInt => Bool;
    Le: Int4, PositiveInt => Bool;
    Le: Int8, PositiveInt => Bool;
    Le: Mood, Mood => Bool;
    Le: Numeric, PositiveInt => Bool;
    Le: PositiveInt, Float4 => Bool;
    Le: PositiveInt, Float8 => Bool;
    Le: PositiveInt, Int2 => Bool;
    Le: PositiveInt, Int4 => Bool;
    Le: PositiveInt, Int8 => Bool;
    Le: PositiveInt, Numeric => Bool;
    Le: PositiveInt, PositiveInt => Bool;
    Le: PriceTag, PriceTag => Bool;
    Lt: Float4, PositiveInt => Bool;
    Lt: Float8, PositiveInt => Bool;
    Lt: Int2, PositiveInt => Bool;
    Lt: Int4, PositiveInt => Bool;
    Lt: Int8, PositiveInt => Bool;
    Lt: Mood, Mood => Bool;
    Lt: Numeric, PositiveInt => Bool;
    Lt: PositiveInt, Float4 => Bool;
    Lt: PositiveInt, Float8 => Bool;
    Lt: PositiveInt, Int2 => Bool;
    Lt: PositiveInt, Int4 => Bool;
    Lt: PositiveInt, Int8 => Bool;
    Lt: PositiveInt, Numeric => Bool;
    Lt: PositiveInt, PositiveInt => Bool;
    Lt: PriceTag, PriceTag => Bool;
    Minus: Cidr, PositiveInt => Inet;
    Minus: Date, PositiveInt => Date;
    Minus: Float4, PositiveInt => Float8;
    Minus: Float8, PositiveInt => Float8;
    Minus: Inet, PositiveInt => Inet;
    Minus: Int2, PositiveInt => Int4;
    Minus: Int4, PositiveInt => Int4;
    Minus: Int8, PositiveInt => Int8;
    Minus: Jsonb, PositiveInt => Jsonb;
    Minus: Numeric, PositiveInt => Numeric;
    Minus: PositiveInt, Float4 => Float8;
    Minus: PositiveInt, Float8 => Float8;
    Minus: PositiveInt, Int2 => Int4;
    Minus: PositiveInt, Int4 => Int4;
    Minus: PositiveInt, Int8 => Int8;
    Minus: PositiveInt, Numeric => Numeric;
    Minus: PositiveInt, PositiveInt => Int4;
    Mul: Float4, PositiveInt => Float8;
    Mul: Float8, PositiveInt => Float8;
    Mul: Int2, PositiveInt => Int4;
    Mul: Int4, PositiveInt => Int4;
    Mul: Int8, PositiveInt => Int8;
    Mul: Interval, PositiveInt => Interval;
    Mul: Money, PositiveInt => Money;
    Mul: Numeric, PositiveInt => Numeric;
    Mul: PositiveInt, Float4 => Float8;
    Mul: PositiveInt, Float8 => Float8;
    Mul: PositiveInt, Int2 => Int4;
    Mul: PositiveInt, Int4 => Int4;
    Mul: PositiveInt, Int8 => Int8;
    Mul: PositiveInt, Interval => Interval;
    Mul: PositiveInt, Money => Money;
    Mul: PositiveInt, Numeric => Numeric;
    Mul: PositiveInt, PositiveInt => Int4;
    Mul: PositiveInt, Time => Interval;
    Mul: Time, PositiveInt => Interval;
    Ne: Float4, PositiveInt => Bool;
    Ne: Float8, PositiveInt => Bool;
    Ne: Int2, PositiveInt => Bool;
    Ne: Int4, PositiveInt => Bool;
    Ne: Int8, PositiveInt => Bool;
    Ne: Mood, Mood => Bool;
    Ne: Numeric, PositiveInt => Bool;
    Ne: PositiveInt, Float4 => Bool;
    Ne: PositiveInt, Float8 => Bool;
    Ne: PositiveInt, Int2 => Bool;
    Ne: PositiveInt, Int4 => Bool;
    Ne: PositiveInt, Int8 => Bool;
    Ne: PositiveInt, Numeric => Bool;
    Ne: PositiveInt, PositiveInt => Bool;
    Ne: PriceTag, PriceTag => Bool;
    Plus: Cidr, PositiveInt => Inet;
    Plus: Date, PositiveInt => Date;
    Plus: Float4, PositiveInt => Float8;
    Plus: Float8, PositiveInt => Float8;
    Plus: Inet, PositiveInt => Inet;
    Plus: Int2, PositiveInt => Int4;
    Plus: Int4, PositiveInt => Int4;
    Plus: Int8, PositiveInt => Int8;
    Plus: Numeric, PositiveInt => Numeric;
    Plus: PositiveInt, Cidr => Inet;
    Plus: PositiveInt, Date => Date;
    Plus: PositiveInt, Float4 => Float8;
    Plus: PositiveInt, Float8 => Float8;
    Plus: PositiveInt, Inet => Inet;
    Plus: PositiveInt, Int2 => Int4;
    Plus: PositiveInt, Int4 => Int4;
    Plus: PositiveInt, Int8 => Int8;
    Plus: PositiveInt, Numeric => Numeric;
    Plus: PositiveInt, PositiveInt => Int4;
    Pow: Float4, PositiveInt => Float8;
    Pow: Float8, PositiveInt => Float8;
    Pow: Int2, PositiveInt => Float8;
    Pow: Int4, PositiveInt => Float8;
    Pow: Int8, PositiveInt => Float8;
    Pow: Numeric, PositiveInt => Numeric;
    Pow: PositiveInt, Float4 => Float8;
    Pow: PositiveInt, Float8 => Float8;
    Pow: PositiveInt, Int2 => Float8;
    Pow: PositiveInt, Int4 => Float8;
    Pow: PositiveInt, Int8 => Float8;
    Pow: PositiveInt, Numeric => Numeric;
    Pow: PositiveInt, PositiveInt => Float8;
    RecEq: PriceTag, PriceTag => Bool;
    RecGe: PriceTag, PriceTag => Bool;
    RecGt: PriceTag, PriceTag => Bool;
    RecLe: PriceTag, PriceTag => Bool;
    RecLt: PriceTag, PriceTag => Bool;
    RecNe: PriceTag, PriceTag => Bool;
    Rem: Int2, PositiveInt => Int4;
    Rem: Int4, PositiveInt => Int4;
    Rem: Int8, PositiveInt => Int8;
    Rem: Numeric, PositiveInt => Numeric;
    Rem: PositiveInt, Int2 => Int4;
    Rem: PositiveInt, Int4 => Int4;
    Rem: PositiveInt, Int8 => Int8;
    Rem: PositiveInt, Numeric => Numeric;
    Rem: PositiveInt, PositiveInt => Int4;
    Shl: Bit, PositiveInt => Bit;
    Shl: Int2, PositiveInt => Int2;
    Shl: Int4, PositiveInt => Int4;
    Shl: Int8, PositiveInt => Int8;
    Shl: PositiveInt, Int2 => Int4;
    Shl: PositiveInt, Int4 => Int4;
    Shl: PositiveInt, PositiveInt => Int4;
    Shl: Varbit, PositiveInt => Bit;
    Shr: Bit, PositiveInt => Bit;
    Shr: Int2, PositiveInt => Int2;
    Shr: Int4, PositiveInt => Int4;
    Shr: Int8, PositiveInt => Int8;
    Shr: PositiveInt, Int2 => Int4;
    Shr: PositiveInt, Int4 => Int4;
    Shr: PositiveInt, PositiveInt => Int4;
    Shr: Varbit, PositiveInt => Bit;
    Xor: Int2, PositiveInt => Int4;
    Xor: Int4, PositiveInt => Int4;
    Xor: Int8, PositiveInt => Int8;
    Xor: PositiveInt, Int2 => Int4;
    Xor: PositiveInt, Int4 => Int4;
    Xor: PositiveInt, Int8 => Int8;
    Xor: PositiveInt, PositiveInt => Int4;
}

surus::prefix_operators! {
    Abs "@": PositiveInt => Int4;
    Cbrt "||/": PositiveInt => Float8;
    Neg "-": PositiveInt => Int4;
    Not "~": PositiveInt => Int4;
    Sqrt "|/": PositiveInt => Float8;
    UnaryPlus "+": PositiveInt => Int4;
}

surus::casts! {
    Bit => PositiveInt;
    Bool => PositiveInt;
    Bpchar => Mood, PositiveInt, PriceTag;
    Bytea => PositiveInt;
    Char => PositiveInt;
    Float4 => PositiveInt;
    Float8 => PositiveInt;
    Int2 => PositiveInt;
    Int4 => PositiveInt;
    Int8 => PositiveInt;
    Jsonb => PositiveInt;
    Mood => Bpchar, Text, Varchar;
    Numeric => PositiveInt;
    PositiveInt => Bit, Bool, Bpchar, Bytea, Char, Float4, Float8, Int2, Int4, Int8, Money, Numeric, Text, Varchar;
    PriceTag => Bpchar, Text, Varchar;
    Text => Mood, PositiveInt, PriceTag;
    Varchar => Mood, PositiveInt, PriceTag;
}
